---
- name: Get device information
  hosts: junos
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no

  tasks:
    - name: Get software and uptime information
      juniper_junos_rpc:
        rpcs: "get-software-information"
      register: junos_result

    - name: Print response
      debug:
        var: junos_result
